version: '3'
services:
  app:
    build:
      context: .
    platform: linux/amd64
    volumes:
      - './config/config.json:/ai/config.json'
      - './font.ttf:/ai/font.ttf'
      - './data:/ai/data'
    restart: always
    environment:
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true
