services:
  app:
    #build:
    #  context: .
    #platform: linux/amd64
    image: ghcr.io/chan-mai/ai:latest
    volumes:
      - './config.json:/ai/config/config.json'
      - './font.ttf:/ai/font.ttf'
      - './data:/ai/data'
    restart: always
    environment:
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true
